### ISSUE TITLE
Error at 'or'

### ISSUE THREAD

**Issue by BuckWoody** [David-Seis/SecureYourAzureData#224]
On - https://github.com/David-Seis/SecureYourAzureData/blob/main/SQLSecurity/02%20-%20SQLServerSecurityBasics.md 

This throws an error: 

DECLARE @Loginid tinyint

    SET @Loginid = '' or 1=1-- '
    --user input = ' or 1=1-- 
    SELECT * 
    FROM Patient
    WHERE loginid = @Loginid --parameterized input

    
    SET @Loginid = 3 
    --user input = 3
    SELECT * 
    FROM Patient
    WHERE loginid = @Loginid --parameterized input

**Comment by David-Seis** [comment]
This is on purpose to show that a malicious input string will not be accepted. This paired with the following error handling section where the malicious actor will not get mor information about what the problem was.
