### ISSUE TITLE
Same or error in Error handling Activity

### ISSUE THREAD

**Issue by BuckWoody** [David-Seis/SecureYourAzureData#225]
https://github.com/David-Seis/SecureYourAzureData/blob/main/SQLSecurity/02%20-%20SQLServerSecurityBasics.md
On this page in the Error Handling section, throws error: 

   DECLARE @Loginid tinyint
      BEGIN TRY
        SET @Loginid = '' or 1=1--' 
        --user input = ' or 1=1--
            SELECT * 
            FROM Patient
            WHERE loginid = @Loginid --parameterized input
      END TRY
      BEGIN CATCH
        Print 'Please use only your user ID'
      END CATCH

    DECLARE @Loginid tinyint
      BEGIN TRY
        SET @Loginid = '3'
        --user input = 3
            SELECT * 
            FROM Patient
            WHERE loginid = @Loginid --parameterized input
      END TRY
      BEGIN CATCH
        Print 'Please use only your user ID'
      END CATCH

**Comment by David-Seis** [comment]
The error her should be “please use only your user I’d” this is to show error handling in contrast to the previous error where it returned the issue to the user
