### ISSUE TITLE
Database Encryption Fails

### ISSUE THREAD

**Issue by BuckWoody** [David-Seis/SecureYourAzureData#226]
https://github.com/David-Seis/SecureYourAzureData/blob/main/SQLSecurity/02%20-%20SQLServerSecurityBasics.md

In this module, the Encrypt the test Database Activity Fails with "cannot find TDE-Cert":

    USE SQLSecurityTest
    GO

    /*Create Encryption key*/
    CREATE DATABASE ENCRYPTION KEY
      WITH ALGORITHM = AES_256
      ENCRYPTION BY SERVER CERTIFICATE TDE_Cert;
    GO

    /* Encrypt database */
    ALTER DATABASE SQLSecurityTest SET ENCRYPTION ON;
    GO

**Comment by David-Seis** [comment]
I am unable to use scalar variables in the backup key command, I have added instructions for this step to specify creating the folder, adding SQL server permissions
