### ISSUE TITLE
change link to include right click and open in new window

### ISSUE THREAD

**Issue by IrishSQL** [David-Seis/SecureYourAzureData#251]
Secure your Azure Data 01
Open [this reference, and review the video](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score?view=o365-worldwide) you see near the top of the page. If there is time in the course, you can follow those instructions to run the evaluation.

**Comment by BuckWoody** [comment]
Thanks for that! There's a note in the main README to do that for all links. I have it right in the link code, but github does not honor the "target" variable in HTML. :(
