### ISSUE TITLE
Why not using SQL Server 2022?

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#257]
00 Pre-Requisites - Activity 2.
You will install SQL Server 2019.
Later it says "This course will cover some of the security features of SQL Server 2022, in a demonstration fashion. If you would like to install SQL Server 2022 instead of SQL Server 2019, check this reference."
Why not using SQL Server 2022 instead of SQL 2019?

**Comment by BuckWoody** [comment]
Because it's not out and people can't use it in production. :) Also, it is mentioned as an option. Also, we will change this to 2022 when it is released.
