### ISSUE TITLE
A workstation or a server

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#258]
00 Pre-Requisites - Activity 2 - Create your own Workstation - Microsoft Azure Virtual Machine

Select a system that has at least 2 processors, a minimum of 8GB of RAM - which system? A workstation or a server?
Or doesn't this really matter for the workshop? In the other options we mention a workstation so I'm assuming a workstation in Azure is also fine.

**Comment by BuckWoody** [comment]
We'll mention this in class.
