### ISSUE TITLE
After installing Python using Chocolatey, I had to reboot my VM before I could install the package manager for Python.

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#260]
After installing Python using Chocolatey, I had to reboot my VM before I could install the package manager for Python.
Without the reboot the commands
python -m pip install -U pip
python -m pip install pyodbc

didn't do anything. 
After the reboot it worked.

**Comment by BuckWoody** [comment]
Interesting - did you use a fresh VM as instructed or something already installed?

**Comment by Pietervanhove** [comment]
I used a fresh VM with Windows 11 in Azure

**Comment by David-Seis** [comment]
I have added a note that a restart may be necessary for some users, thank  you Pieter!
