### ISSUE TITLE
Roles - Activity: Create and assign Roles - python SimpleConnection.py

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#265]
At the end there is mentioned 

"Note, Windows users will only be able to connect via a Trusted connection. Please run powershell as User1 and User2 to see their connection results. You can read more about how to run a command as another user at this reference."

Perhaps it's better to add an example here as well. We know User1 and 2 and the password because they were created before.
When I runas User1 or 2 I just see a black box popping up for 1ms so I was unable to verify what the connection result was.
Is this expected behavior?

**Comment by BuckWoody** [comment]
Agree on this. Let's change it after current deliveries.

**Comment by David-Seis** [comment]
Will review for second release!
