### ISSUE TITLE
Activity: Test access through Roles - Steps - Make the script more clean

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#268]
Add a table to the Sample 'SQLSecurityTest' database
Make the script cleaner like Capital characters for the data types and the column names in the insert statement are all in small characters.

**Comment by BuckWoody** [comment]
Agree on the code formatting. David, I will show you a tool to do this, but let's wait until after the first deliveries to change anything since we are so close. I only want to fix broken code at this point.

**Comment by David-Seis** [comment]
Understood!

**Comment by David-Seis** [comment]
We will review this for the second release!
