### ISSUE TITLE
Activity: Test access through Roles - Steps - experiment with

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#271]
At the end of the chapter there is mentioned
"You now have a series of Securables and Principals, and you can experiment with SELECT and EXECUTE statements in T-SQL and from the Python Application to see the effects."

I think it's better if we give the student some example scripts instead of telling them to "experiment".

**Comment by BuckWoody** [comment]
We have a full Notebook for that which is called out in the last Module. Also, this lets us contract or expand the time for different students. This has worked well for us in many workshops in the past.
