### ISSUE TITLE
2.4 Applications - Row Level Security

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#276]
"you can restrict access to objects based on the security context of the user". This is not correct, you don't restrict access to an object but to rows in a specific table based on a function. Row-Level Security enables you to use group membership or execution context to control access to rows in a database table.

**Comment by BuckWoody** [comment]
Good catch. I'll edit.

**Comment by David-Seis** [comment]
Fixed, thank you Pieter!
