### ISSUE TITLE
2.4 Applications - SQL Ledger

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#278]
The feature is called ledger, not SQL Ledger.
I would change the description into.

Each transaction that the database executes is cryptographically hashed (SHA-256). Transactions are then cryptographically linked together, like a Blockchain. Cryptographically hashed database digests represent the state of the database. They're periodically generated and stored outside Azure SQL Database or SQL Server 2022 in a tamper-proof storage location such as Azure immutable Blob storage or Azure Confidential Ledger. All historical data of ledger tables is transparently maintained in the database system and exposed to users for auditing and forensic purposes. Historical data can be used to analyze the operations executed on and detect unexpected or malicious modifications. However, malicious high privileged users or cloud operators can update the content of ledger tables, using other techniques like writing directly to the data files, and tamper with the data.  These "under the covers attacks" will be detected through the cryptographic verification. Database digests can be used by auditors, business partners (in case of a multi-party scenario) or even end users to execute the database verification process that recomputes the hashes in the database and compares them to the input hashes provided by the user. When the verification is successful, you will have cryptographic proof that your data can be fully trusted.

**Comment by David-Seis** [comment]
We have made the naming edit, and will review the description for the second release!
