### ISSUE TITLE
2.4 Applications - SQL Ledger - Activity: Review SQL Ledger

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#279]
Azure SQL DB should be used here or SQL Server 2022 is required.
In the prerequisites we mention that SQL Server 2019 should be installed so for this Activity Azure SQL DB should be used.

**Comment by BuckWoody** [comment]
Right - we'll be clear about that in the class, but I should have that called out in the text as well.

**Comment by David-Seis** [comment]
We will review this for the next release.
