### ISSUE TITLE
2.4 Applications - Preventing SQL Injection Attacks - Activity: Parameterized Queries and Error Handling

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#280]
Run this Query for a client to see their account information as a general user
Query should be with lower q 
The query is on the patient table so it should be
"Run this query to retrieve information from 1 patient"

Also the   
 USE [SQLSecurityTest]
GO
is missing

**Comment by David-Seis** [comment]
Fixed and added!
