### ISSUE TITLE
2.4 Applications - Preventing SQL Injection Attacks - Activity: Parameterized Queries and Error Handling - 3

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#282]
Add Error Handling
Typo mroe 
The script doesn't work
SET @Loginid = '' or 1=1--'
@Loginid is declared twice
The CATCH is never executed so the Error handling is never showed by using the script.

**Comment by David-Seis** [comment]
Fixed, thank you!
