### ISSUE TITLE
2.6 Auditing - Activity: Create a Server Audit - Add a few more server-audits that can be useful in your organization

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#288]
Add a few more server-audits that can be useful in your organization
should be
Add a few more server audits and server audit specifications that can be useful in your organization
After creation, nothing happens with these audits.
I think it would be interesting to also add a script that triggers the server audit like adding a new server login.

**Comment by David-Seis** [comment]
This is intentional, the output is shown in the accompanying notebook. We had this audit running for all of the previous activities and see the output in the notebook!
