### ISSUE TITLE
3.1 Accessing Azure SQL DB - Microsoft Azure Firewalls

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#290]
Nothing is mentioned about Virtual Networks, Private endpoints, Restrict Outbound networking, Connection Policy.
Basically networking in general is missing

**Comment by BuckWoody** [comment]
It's covered in the reference pointed to in this section - although we can expand it in rev 2. 
https://github.com/David-Seis/SecureYourAzureData/blob/main/SQLSecurity/03%20-%20SQLAzureSecurity.md#01
