### ISSUE TITLE
3.2 Principals - Activity: Create and List Users - Steps

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#292]
Typo conencted ot

**Comment by BuckWoody** [comment]
Not sure what this is - David, can you investigate?

**Comment by Pietervanhove** [comment]
Under steps you have step 1
Run the following code on your test SQL Azure DB conencted ot the master database:
should be
Run the following code on your test SQL Azure DB connected to the master database:

**Comment by David-Seis** [comment]
Thank you, fixed!
