### ISSUE TITLE
3.2 Principals - missing contained database users

### ISSUE THREAD

**Issue by Pietervanhove** [David-Seis/SecureYourAzureData#293]
I think we should also add the contained database users which is a best practice for Azure SQL DB.

**Comment by BuckWoody** [comment]
You mean create them in the code sample or do you mean have a deeper discussion of that?

**Comment by Pietervanhove** [comment]
Both yes. Contained Database users are important for Azure SQL DB and it's not really mentioned.

**Comment by David-Seis** [comment]
Thank you Pieter, we will add this in the next release.
